// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.29.3

package com.exchange.system.protocol;

public final class Message {
  private Message() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Message.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProviderMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProviderMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    java.util.List<com.exchange.system.protocol.Message.ProviderMessage.MessageItem> 
        getItemsList();
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    com.exchange.system.protocol.Message.ProviderMessage.MessageItem getItems(int index);
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    java.util.List<? extends com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProviderMessage}
   */
  public static final class ProviderMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProviderMessage)
      ProviderMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ProviderMessage.class.getName());
    }
    // Use ProviderMessage.newBuilder() to construct.
    private ProviderMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProviderMessage() {
      items_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.system.protocol.Message.internal_static_ProviderMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.system.protocol.Message.internal_static_ProviderMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.system.protocol.Message.ProviderMessage.class, com.exchange.system.protocol.Message.ProviderMessage.Builder.class);
    }

    public interface MessageItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ProviderMessage.MessageItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string symbol = 1;</code>
       * @return The symbol.
       */
      java.lang.String getSymbol();
      /**
       * <code>string symbol = 1;</code>
       * @return The bytes for symbol.
       */
      com.google.protobuf.ByteString
          getSymbolBytes();

      /**
       * <code>double price = 2;</code>
       * @return The price.
       */
      double getPrice();

      /**
       * <code>bool priceChange = 3;</code>
       * @return The priceChange.
       */
      boolean getPriceChange();
    }
    /**
     * Protobuf type {@code ProviderMessage.MessageItem}
     */
    public static final class MessageItem extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ProviderMessage.MessageItem)
        MessageItemOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 3,
          /* suffix= */ "",
          MessageItem.class.getName());
      }
      // Use MessageItem.newBuilder() to construct.
      private MessageItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private MessageItem() {
        symbol_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.exchange.system.protocol.Message.internal_static_ProviderMessage_MessageItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.exchange.system.protocol.Message.internal_static_ProviderMessage_MessageItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.exchange.system.protocol.Message.ProviderMessage.MessageItem.class, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder.class);
      }

      public static final int SYMBOL_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 1;</code>
       * @return The symbol.
       */
      @java.lang.Override
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        }
      }
      /**
       * <code>string symbol = 1;</code>
       * @return The bytes for symbol.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PRICE_FIELD_NUMBER = 2;
      private double price_ = 0D;
      /**
       * <code>double price = 2;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }

      public static final int PRICECHANGE_FIELD_NUMBER = 3;
      private boolean priceChange_ = false;
      /**
       * <code>bool priceChange = 3;</code>
       * @return The priceChange.
       */
      @java.lang.Override
      public boolean getPriceChange() {
        return priceChange_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 1, symbol_);
        }
        if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
          output.writeDouble(2, price_);
        }
        if (priceChange_ != false) {
          output.writeBool(3, priceChange_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(1, symbol_);
        }
        if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, price_);
        }
        if (priceChange_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, priceChange_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.exchange.system.protocol.Message.ProviderMessage.MessageItem)) {
          return super.equals(obj);
        }
        com.exchange.system.protocol.Message.ProviderMessage.MessageItem other = (com.exchange.system.protocol.Message.ProviderMessage.MessageItem) obj;

        if (!getSymbol()
            .equals(other.getSymbol())) return false;
        if (java.lang.Double.doubleToLongBits(getPrice())
            != java.lang.Double.doubleToLongBits(
                other.getPrice())) return false;
        if (getPriceChange()
            != other.getPriceChange()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
        hash = (53 * hash) + getSymbol().hashCode();
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPrice()));
        hash = (37 * hash) + PRICECHANGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPriceChange());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.exchange.system.protocol.Message.ProviderMessage.MessageItem prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ProviderMessage.MessageItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ProviderMessage.MessageItem)
          com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.exchange.system.protocol.Message.internal_static_ProviderMessage_MessageItem_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.exchange.system.protocol.Message.internal_static_ProviderMessage_MessageItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.exchange.system.protocol.Message.ProviderMessage.MessageItem.class, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder.class);
        }

        // Construct using com.exchange.system.protocol.Message.ProviderMessage.MessageItem.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          symbol_ = "";
          price_ = 0D;
          priceChange_ = false;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.exchange.system.protocol.Message.internal_static_ProviderMessage_MessageItem_descriptor;
        }

        @java.lang.Override
        public com.exchange.system.protocol.Message.ProviderMessage.MessageItem getDefaultInstanceForType() {
          return com.exchange.system.protocol.Message.ProviderMessage.MessageItem.getDefaultInstance();
        }

        @java.lang.Override
        public com.exchange.system.protocol.Message.ProviderMessage.MessageItem build() {
          com.exchange.system.protocol.Message.ProviderMessage.MessageItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.exchange.system.protocol.Message.ProviderMessage.MessageItem buildPartial() {
          com.exchange.system.protocol.Message.ProviderMessage.MessageItem result = new com.exchange.system.protocol.Message.ProviderMessage.MessageItem(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(com.exchange.system.protocol.Message.ProviderMessage.MessageItem result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.symbol_ = symbol_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.price_ = price_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.priceChange_ = priceChange_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.exchange.system.protocol.Message.ProviderMessage.MessageItem) {
            return mergeFrom((com.exchange.system.protocol.Message.ProviderMessage.MessageItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.exchange.system.protocol.Message.ProviderMessage.MessageItem other) {
          if (other == com.exchange.system.protocol.Message.ProviderMessage.MessageItem.getDefaultInstance()) return this;
          if (!other.getSymbol().isEmpty()) {
            symbol_ = other.symbol_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.getPrice() != 0D) {
            setPrice(other.getPrice());
          }
          if (other.getPriceChange() != false) {
            setPriceChange(other.getPriceChange());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  symbol_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 17: {
                  price_ = input.readDouble();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 17
                case 24: {
                  priceChange_ = input.readBool();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object symbol_ = "";
        /**
         * <code>string symbol = 1;</code>
         * @return The symbol.
         */
        public java.lang.String getSymbol() {
          java.lang.Object ref = symbol_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            symbol_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string symbol = 1;</code>
         * @return The bytes for symbol.
         */
        public com.google.protobuf.ByteString
            getSymbolBytes() {
          java.lang.Object ref = symbol_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            symbol_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string symbol = 1;</code>
         * @param value The symbol to set.
         * @return This builder for chaining.
         */
        public Builder setSymbol(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          symbol_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string symbol = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearSymbol() {
          symbol_ = getDefaultInstance().getSymbol();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string symbol = 1;</code>
         * @param value The bytes for symbol to set.
         * @return This builder for chaining.
         */
        public Builder setSymbolBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          symbol_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private double price_ ;
        /**
         * <code>double price = 2;</code>
         * @return The price.
         */
        @java.lang.Override
        public double getPrice() {
          return price_;
        }
        /**
         * <code>double price = 2;</code>
         * @param value The price to set.
         * @return This builder for chaining.
         */
        public Builder setPrice(double value) {

          price_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>double price = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPrice() {
          bitField0_ = (bitField0_ & ~0x00000002);
          price_ = 0D;
          onChanged();
          return this;
        }

        private boolean priceChange_ ;
        /**
         * <code>bool priceChange = 3;</code>
         * @return The priceChange.
         */
        @java.lang.Override
        public boolean getPriceChange() {
          return priceChange_;
        }
        /**
         * <code>bool priceChange = 3;</code>
         * @param value The priceChange to set.
         * @return This builder for chaining.
         */
        public Builder setPriceChange(boolean value) {

          priceChange_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>bool priceChange = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearPriceChange() {
          bitField0_ = (bitField0_ & ~0x00000004);
          priceChange_ = false;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ProviderMessage.MessageItem)
      }

      // @@protoc_insertion_point(class_scope:ProviderMessage.MessageItem)
      private static final com.exchange.system.protocol.Message.ProviderMessage.MessageItem DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.exchange.system.protocol.Message.ProviderMessage.MessageItem();
      }

      public static com.exchange.system.protocol.Message.ProviderMessage.MessageItem getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<MessageItem>
          PARSER = new com.google.protobuf.AbstractParser<MessageItem>() {
        @java.lang.Override
        public MessageItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<MessageItem> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<MessageItem> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.exchange.system.protocol.Message.ProviderMessage.MessageItem getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.exchange.system.protocol.Message.ProviderMessage.MessageItem> items_;
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.exchange.system.protocol.Message.ProviderMessage.MessageItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    @java.lang.Override
    public com.exchange.system.protocol.Message.ProviderMessage.MessageItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
     */
    @java.lang.Override
    public com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.exchange.system.protocol.Message.ProviderMessage)) {
        return super.equals(obj);
      }
      com.exchange.system.protocol.Message.ProviderMessage other = (com.exchange.system.protocol.Message.ProviderMessage) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.exchange.system.protocol.Message.ProviderMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.exchange.system.protocol.Message.ProviderMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.exchange.system.protocol.Message.ProviderMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.exchange.system.protocol.Message.ProviderMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProviderMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProviderMessage)
        com.exchange.system.protocol.Message.ProviderMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.exchange.system.protocol.Message.internal_static_ProviderMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.exchange.system.protocol.Message.internal_static_ProviderMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.exchange.system.protocol.Message.ProviderMessage.class, com.exchange.system.protocol.Message.ProviderMessage.Builder.class);
      }

      // Construct using com.exchange.system.protocol.Message.ProviderMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
        } else {
          items_ = null;
          itemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.exchange.system.protocol.Message.internal_static_ProviderMessage_descriptor;
      }

      @java.lang.Override
      public com.exchange.system.protocol.Message.ProviderMessage getDefaultInstanceForType() {
        return com.exchange.system.protocol.Message.ProviderMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.exchange.system.protocol.Message.ProviderMessage build() {
        com.exchange.system.protocol.Message.ProviderMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.exchange.system.protocol.Message.ProviderMessage buildPartial() {
        com.exchange.system.protocol.Message.ProviderMessage result = new com.exchange.system.protocol.Message.ProviderMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.exchange.system.protocol.Message.ProviderMessage result) {
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
      }

      private void buildPartial0(com.exchange.system.protocol.Message.ProviderMessage result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.exchange.system.protocol.Message.ProviderMessage) {
          return mergeFrom((com.exchange.system.protocol.Message.ProviderMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.exchange.system.protocol.Message.ProviderMessage other) {
        if (other == com.exchange.system.protocol.Message.ProviderMessage.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.exchange.system.protocol.Message.ProviderMessage.MessageItem m =
                    input.readMessage(
                        com.exchange.system.protocol.Message.ProviderMessage.MessageItem.parser(),
                        extensionRegistry);
                if (itemsBuilder_ == null) {
                  ensureItemsIsMutable();
                  items_.add(m);
                } else {
                  itemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.exchange.system.protocol.Message.ProviderMessage.MessageItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.exchange.system.protocol.Message.ProviderMessage.MessageItem>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.exchange.system.protocol.Message.ProviderMessage.MessageItem, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder, com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public java.util.List<com.exchange.system.protocol.Message.ProviderMessage.MessageItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public com.exchange.system.protocol.Message.ProviderMessage.MessageItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.exchange.system.protocol.Message.ProviderMessage.MessageItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder setItems(
          int index, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder addItems(com.exchange.system.protocol.Message.ProviderMessage.MessageItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.exchange.system.protocol.Message.ProviderMessage.MessageItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder addItems(
          com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder addItems(
          int index, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.exchange.system.protocol.Message.ProviderMessage.MessageItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public java.util.List<? extends com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.exchange.system.protocol.Message.ProviderMessage.MessageItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ProviderMessage.MessageItem items = 1;</code>
       */
      public java.util.List<com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.exchange.system.protocol.Message.ProviderMessage.MessageItem, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder, com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.exchange.system.protocol.Message.ProviderMessage.MessageItem, com.exchange.system.protocol.Message.ProviderMessage.MessageItem.Builder, com.exchange.system.protocol.Message.ProviderMessage.MessageItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProviderMessage)
    }

    // @@protoc_insertion_point(class_scope:ProviderMessage)
    private static final com.exchange.system.protocol.Message.ProviderMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.exchange.system.protocol.Message.ProviderMessage();
    }

    public static com.exchange.system.protocol.Message.ProviderMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProviderMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProviderMessage>() {
      @java.lang.Override
      public ProviderMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProviderMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProviderMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.exchange.system.protocol.Message.ProviderMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProviderMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProviderMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProviderMessage_MessageItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProviderMessage_MessageItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\201\001\n\017ProviderMessage\022+\n\005i" +
      "tems\030\001 \003(\0132\034.ProviderMessage.MessageItem" +
      "\032A\n\013MessageItem\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price" +
      "\030\002 \001(\001\022\023\n\013priceChange\030\003 \001(\010B\'\n\034com.excha" +
      "nge.system.protocolB\007Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProviderMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProviderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProviderMessage_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_ProviderMessage_MessageItem_descriptor =
      internal_static_ProviderMessage_descriptor.getNestedTypes().get(0);
    internal_static_ProviderMessage_MessageItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProviderMessage_MessageItem_descriptor,
        new java.lang.String[] { "Symbol", "Price", "PriceChange", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
